### ISSUE TITLE
Server examples do not compile anymore

### ISSUE THREAD

**Issue by sanmai-NL** [ctz/hyper-rustls#29]
```sh
cargo run --example server
```
```
error: native library `ring-asm` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  ring v0.9.7
  ring v0.11.0
```

**Comment by lucab** [comment]
It works here, you probably have a stale cargo cache in your local machine or you are not building current master. Please `git pull` and `cargo update`, then try again.

**Comment by sanmai-NL** [comment]
Sorry, forgot to include I'm on `hyper-current`, not master. I took a few extra steps including those you requested, compilation still fails withj the error.

**Comment by lucab** [comment]
`hyper-current` has already been fully merged into master, I'm not sure why you would want to use that.

That said, the issue you are seeing has been fixed by https://github.com/ctz/hyper-rustls/pull/25 and is available in master and 0.8. If you can't switch to those, you may consider backporting that commit.

**Comment by sanmai-NL** [comment]
Thanks, the examples work for me too now. Removing the stale branch would be good!

**Comment by ctz** [comment]
unpushed, sorry for the confusion!
