### ISSUE TITLE
UnknownCA error

### ISSUE THREAD

**Issue by azastrael** [ctz/hyper-rustls#45]
# Steps to reproduce

```bash
git clone https://github.com/ctz/hyper-rustls
cd hyper-rustls
cargo run --example server
```
and in an other terminal:
```bash
curl https://127.0.0.1:1337
```

In the first terminal, you should get:
```
Starting to serve on https://127.0.0.1:1337.
FAILED: error accepting connection: received fatal alert: UnknownCA
```

# Expected behavior

The server should not crash when the client return an `UnknownCA` alert and just close the connection.

**Comment by lucab** [comment]
@azastrael the short answer is: your client is sending back a TLS fatal alert as it doesn't trust the CA, and the server is just shutting down in response to that. Use `curl --cacert examples/sample.pem https://localhost:1337` instead.

The longer explanation is that this is an example server we also use for CI testing, so it reacts to anything outside of the expected happy path by exiting (including protocol errors) . It also needs a self-signed certificate for localhost, which is typically not in your default trust store. This means that when you try to plainly curl it, there is an hard-failure at TLS level and both client and server just report it and exit.
I understand this is not the normal expected behavior for an HTTPS server, but at the same time it is very handy for a full roundtrip in CI.

**Comment by atelosotaar** [comment]
How were the sample.pem and sample.rsa files generated? Is this mentioned anywhere ? (can't find it)
I need to generate a pair for `localhost` specifically, because I want to use chromium's `chrome://flags/#allow-insecure-localhost` so that it doesn't fail to connect.

I tried:
`$ openssl req -x509 -sha256 -nodes -newkey rsa:2048 -days 365 -keyout localhost.rsa -out localhost.pem`
but that fails in `cargo run --example server` with `FAILED: expected a single private key`

Is there more than 1 private key in `localhost.rsa` ? I don't get it :)
